### PR TITLE
chore: fix build failure with dune-configurator 2.6.0

### PR DESCRIPTION
**Pull request by glennsl**
`dune-configurator` 2.6.0 seems to be broken, resulting in the build failing with:

```
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/base@opam:v0.14.0
    # esy-build-package: pwd: /home/glennsl/.esy/3/b/opam__s__base-opam__c__v0.14.0-ff1c173d
    # esy-build-package: running: 'dune' 'build' '-p' 'base' '-j' '4'
        discover src/mpopcnt.sexp (exit 2)
    (cd _build/default/src && discover/discover.exe -o mpopcnt.sexp)
    Fatal error: exception Configurator__Import.Fatal_error("Cannot find special file \"/home/glennsl/.esy/3/b/opam__s__base-opam__c__v0.14.0-ff1c173d/_build/default/.dune/configurator.v2\" produced by dune.")
    error: command failed: 'dune' 'build' '-p' 'base' '-j' '4' (exited with 1)
    esy-build-package: exiting with errors above...
    
  building @opam/base@opam:v0.14.0
```

This therefore adds resolutions to pin `dune-configurator` and `dune-private-libs` to 2.5.1. The latter either because its 2.6.0 iteration is broken as well, or at least don't work with `dune-configurator` 2.5.1.

### CODE REVIEW

**Comment by glennsl** [comment]
@rogererens: Looks like you're using clang 11, which hasn't been released yet. clang 10 or older should work.

**Comment by rogererens** [comment]
No, AFAICT I am using clang 10:

roger@T420:~$ clang --version
clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin



Op do 11 jun. 2020 om 11:13 schreef Glenn Slotte <notifications@github.com>:

**Comment by glennsl** [comment]
Hmm, yeah seems like it might be an issue with clang 10 in some cases as well. Either way this has to be fixed in `esy-skia`. Would you open an issue for it there?

**Pull request merged**
