### PR TITLE
Feature/style getter

### LINKED ISSUE #239: Add ability to query a style from a list of styles
This would be particularly helpful for building native components e.g. if a user passes a list of styles like
```reason
<Slider
 style=Style.[color(red)]
/>
```
and you wanted to query this in the component so you could do some logic on basis of a value a user has passed in, I'm working on an `unwrap`
function which allows you to get the raw value a user passed in since
as it actually comes down it would be wrapped in `Color(red)`

### PR DESCRIPTION
**Pull request by Akin909**
@OhadRau I've tried using a GADT as you suggested on discord for the getter, it solves the type issues :+1: but It doesn't match the right value, I tried the example you posted, which does work but once I plug in the actual style values it doesn't catch the right value.

Does anything come to mind from how I've implemented it as to why?
if this works it fixes #239

### CODE REVIEW

**Comment by Akin909** [comment]
Oh I think it might be because the defaults arent from the selector module so they are essentially, not the same so the comparison is failing

**Comment by OhadRau** [comment]
@Akin909 any examples of values that don't work? Or is it not working for anything? The type checker should hopefully catch it if we're returning the wrong thing

**Comment by Akin909** [comment]
@OhadRau none of them work atm its odd because all the types are what's expected, I tried running your example with the values as is and that works but plugging in the values from `allProps` which is the combination of all style prop variants doesn't seem to match only the default clause at the bottom of the switch is hit its almost as though the variants dont match

**Comment by OhadRau** [comment]
@Akin909 looks like the issue is just that the input example doesn't provide a fontfamily so it's always going to fail. Editing that file worked on my end, if you want I can push the code that I used for that.

**Comment by Akin909** [comment]
@OhadRau completely right :man_facepalming: * 20 thanks for checking it out, was just a case of testing the an absent value which is why I kept getting the default SIGH :laughing:, will add some tests to this and replace the boilerplate we've been using to solve this problem

**Comment by bryphe** [comment]
Thanks @Akin909 for implementing this + tests, and @OhadRau for the help and review! The Selector does look a lot simpler to use 👍

**Pull request merged**
