### PR TITLE
Feature/tree component

### LINKED ISSUE #246: UI - Component: Tree View
It'd be helpful to have a default 'tree-view' style component available. 

Some possible API ideas:
- react-treeview: https://github.com/chenglou/react-treeview
- react-ui-tree: https://github.com/pqx/react-ui-tree
- react-treebeard: https://github.com/storybooks/react-treebeard

We could use font-awesome to find some good icons for expand/collapsed state (or even use triangles from the border styling: https://css-tricks.com/snippets/css/css-triangle/)

### PR DESCRIPTION
**Pull request by Akin909**
This fixes #246 
treeview

### CODE REVIEW

**Comment by bryphe** [comment]
Thanks for the work here, @Akin909 ! I like the way you enabled a custom rendering strategy for the tree, that's great. The component feels very concise and easy to understand.

I'm wondering if we could tweak the examples a bit, visually?

The custom renderer is funny but it was hard for me to follow - like I see "terrible song, awful person" as a child of "awesome tunes, cool dude" and thought it was a bug 😄

For the `Show Empty Nodes` - could we showcase what a child node would look like? The 'X's were a bit confusing for me. Maybe we could title one side 'Custom Render' and the other 'Default Renderer'.

A couple other minor design feedback for the example:
- Could we wrap the entire container in a <View /> and vertically center it?
- Could we put a bit more spacing + a border or line in between them to visually differentiate the two trees?

Thanks for your work on this, Akin! Can't wait until we can use it for the explorer for Oni 2 😍

**Comment by Akin909** [comment]
@bryphe thanks for the review, yeah the examples are a bit sloppy (particular the record one) was actually already making some of the changes you recommended locally so will push that once its tied up

**Comment by Akin909** [comment]
Side note: making examples is pretty hard since all my sizing is completely out of whack no idea how any of these things will look on someone else's machine

**Comment by OhadRau** [comment]
I guess all trees are binary trees here. Could we do it more generally with any number of children? I think that would be needed for a file browser for example

**Comment by Akin909** [comment]
Seems to be the flaky CI happening here the build etc. all pass

**Comment by Akin909** [comment]
could use a hand with the CI here @bryphe tried re-pushing but it still fails in CI but runs locally

**Comment by bryphe** [comment]
> Side note: making examples is pretty hard since all my sizing is completely out of whack no idea how any of these things will look on someone else's machine

Definitely - we need to fix this issue - sorry it's a pain right now. We don't handle 'scaling' correctly - need to fix this using calculations from `glfwGetMonitorPhysicalSize` in #226. 

> could use a hand with the CI here @bryphe tried re-pushing but it still fails in CI but runs locally

Restarted! And green now 😄 

Code changes look good to me @Akin909 , thanks for updating the examples!

**Pull request merged**
