### PR TITLE
Add ~easing parameter to transition hook.

### PR DESCRIPTION
**Pull request by Et7f3**
Thanks for @zbaylin. He notice (on discord) I have forgotten ~easing parameter in #625. This PR fix this.

### CODE REVIEW

**Comment by lessp** [comment]
I want this! 😄

**Comment by glennsl** [comment]
Good luck rebasing! 😛 Probably easier to start this one from scratch :)

**Comment by Et7f3** [comment]
It fail on MacOS with error 127 from discord it may be due to large build env: I have  open a PR to try to reduce it to strictly necessary. https://github.com/bryphe/reason-gl-matrix/pull/22

**Comment by Et7f3** [comment]
Just failing for formatting but seem that reason-gl-matrix build seem fixed. Hope it is really fixed.

**Comment by Et7f3** [comment]
It was hard to rebase with lock file 😂.

**Pull request merged**
