### PR TITLE
add support for flexWrap

### LINKED ISSUE #283: Style is missing flexWrap
If I understand correctly you using Yoga under the hood and it already supports flexWrap: https://yogalayout.com/docs/flex-wrap/

Is there a reason why it's not supported or is this an easy addition? Happy to open a PR: https://github.com/revery-ui/revery/blob/master/src/UI/Style.re#L35-L38

### PR DESCRIPTION
**Pull request by nikgraf**
Closes #283

### CODE REVIEW

**Comment by nikgraf** [comment]
@bryphe something seems to wrong with the azure cache/install?!?

**Comment by nikgraf** [comment]
@Akin909 can you possibly help put here?

**Comment by bryphe** [comment]
Sorry for the build issues! Thanks for the contribution @nikgraf (and thank you for reviewing @OhadRau !) Looking into the CI failure.

**Comment by bryphe** [comment]
Looks like a transient build failure when it was building the OCaml compiler on Windows (it uses `git` to get the latest `flexdll`, but that failed for some reason). Not related to this change; I'll merge it right now. Thanks again for the contribution @nikgraf !

**Pull request merged**
