### PR TITLE
Fix rendering of glyph clusters

### PR DESCRIPTION
**Pull request by msvbg**
Clusters like ligatures currently render incorrectly. Here is a picture of the problem:

sample

In the first case, I'm assuming that the font I'm using cannot render Z͒̀͆ͯaͣ̈̋̐ͤͥ͗l͗ͮ͑ͮ͑ͥ͌g̔o̐͗͌͊ͮ̒.ͬ̒̃̃́ properly. But the version to the right looks far better than the version to the left! In the second case, the `fi` ligature in the typeface messes with the font rendering to cause the `r` to render twice at the end.

### CODE REVIEW

**Comment by Akin909** [comment]
@msvbg thanks for picking this up and for the PR. I think the CI is failing because you need to run `esy format` on the code to so `refmt` gets autoformats it here and in you're other PR as well :+1:

**Comment by msvbg** [comment]
Thanks @Akin909. Will try this.

**Comment by msvbg** [comment]
@Akin909 It seems that it's still breaking. The CI log is not telling me much, either.

**Comment by bryphe** [comment]
Just tested this out @msvbg - looks great! Thank you for the contribution. 

It looks like the build failure is due to a problem with the lock files - I reverted the lock file changes and it seems like the hygiene check passes. I'll push that to your branch, and then bring this once the build is green.

**Pull request merged**
