### PR TITLE
Dependency: Upgrade reason-harfbuzz

### PR DESCRIPTION
**Pull request by bryphe**
This prunes the link flags brought in by `reason-harfbuzz`, and fixes a bug where images wouldn't load on linux builds.

### CODE REVIEW

**Comment by zbaylin** [comment]
Oops! I didn't see this before I made #742. Hopefully this is sufficient to close that!

**Comment by bryphe** [comment]
@zbaylin - me too! 🤞 Would you mind testing this out and see if it fixes it?

Unfortunately I can't reproduce, so this is really just a guess.

**Comment by zbaylin** [comment]
Unfortunately this didn't fix it. I still get the linking error. I can post a more detailed one, but I don't want to spam Github issues.

**Comment by bryphe** [comment]
Fixed in #758

**Pull request closed without merging**
