### PR TITLE
TodoMVC example revamp

### PR DESCRIPTION
**Pull request by glennsl**
Prettied it up a bit to showcase revery's capabilities better, and got it close to feature parity with the actual TodoMVC. 

Design-wise it's still pretty challenging. I encountered a number of bugs and missing features (which was also partly my intention with this).

### CODE REVIEW

**Comment by glennsl** [comment]
The CI failure looks like a fluke to me. Failing to build `reason-gl-matrix` on macOS.

**Comment by lessp** [comment]
> The CI failure looks like a fluke to me. Failing to build `reason-gl-matrix` on macOS.

https://github.com/bryphe/reason-gl-matrix/blob/master/package.json#L14

I wonder if there'd be a difference if `refmterr` was used as a devDep and only used in `buildDev`. Remember seeing something similar. @Et7f3 might know more?

**Comment by Et7f3** [comment]
I have seen https://github.com/esy/esy/pull/953 and https://github.com/esy/esy/commit/66baf4df2e8274d95a4e05e9b319c3561f056450 but it isn't released.

**Comment by bryphe** [comment]
Wow! So much nicer 😍 

image

**Comment by bryphe** [comment]
Might need to make this our new 'default' example...

**Comment by glennsl** [comment]
Oh wow, that looks so much more purple on my Macbook than it does on my desktop. It was supposed to be subtle, lol 😆I might have to tweak those colors a bit 😁

**Comment by bryphe** [comment]
Still a _huge_ improvement! 🎉

**Comment by glennsl** [comment]
Looks decently well on both Macbook and desktop now. Slightly pinker on the desktop, but oh well...

**Comment by bryphe** [comment]
It looks amazing! Really impressed with the improvements @glennsl 😍 Bringing this in now-

**Pull request merged**
