### PR TITLE
chore: use rebez and rench as deps instead of resolutions

### PR DESCRIPTION
**Pull request by lessp**
Would it work to use these as `dependencies` instead of resolutions?

### CODE REVIEW

**Comment by bryphe** [comment]
Unfortunately I don't think we can bring these in as `devDeps` because they're actually used at runtime (aka, they are real `deps`). We could publish NPM packages for them, though, so we don't need the resolution 👍

**Comment by lessp** [comment]
> Unfortunately I don't think we can bring these in as `devDeps` because they're actually used at runtime (aka, they are real `deps`). We could publish NPM packages for them, though, so we don't need the resolution 👍

Sorry, looks like I was tired while submitting this! 😄

What I really meant was if we could replace the `*` in `"dependenices"` (and remove them in resolutions) to point directly to the Github-repo, meaning that consumers would not have to specify the resolutions for these as well!

**Comment by lessp** [comment]
I think this is good to merge, unless I'm missing any potential issues this could create! It removes the noise to have to specify the resolutions for `rench` and `rebez` when consuming Revery!

**Comment by bryphe** [comment]
Oh nice, thanks a lot for fixing this up @lessp ! 🎉 

>  It removes the noise to have to specify the resolutions for rench and rebez when consuming Revery!

Definitely! Ideally it's just a dependency on `revery` and you're good to go 👍 

Looks good to me - bringing this in now!

**Pull request merged**
